// Todos los textos visibles del juego viven aquí (cambiar idioma = cambiar estos datos).
export const STR = {
  title: "CAFE RACER 93",
  subtitle: "SYNTHWAVE HIGHWAY",
  start: "ACELERAR",
  startHint: "ESPACIO / TOCA / ▶ del control",
  controls: "← →  /  A D  esquivar    ·    ↑ ↓ acelerar/frenar    ·    toca izq/der en móvil",
  hudSpeed: "VEL",
  hudScore: "PUNTOS",
  hudDist: "DIST",
  hudBest: "RÉCORD",
  hudBusters: "BUSTERS",
  hudMult: "MULT",
  hudRecordHoy: "RÉCORD HOY",
  paused: "EN PAUSA",
  resumeHint: "click para volver",
  gameOver: "CHOCASTE",
  finalScore: "PUNTOS",
  newBest: "¡NUEVO RÉCORD!",
  retry: "REINTENTAR",
  retryHint: "ESPACIO / TOCA / ▶",
  loading: "CARGANDO MOTO…",
  unitSpeed: "km/h",
  unitDist: "m",
  // ---- TIENDA (textos por datos; el render de la tienda los lee) ----
  shopTitle: "TIENDA",
  shopBalance: "BUSTERS DISPONIBLES",
  shopWallet: "BILLETERA",
  shopSkins: "SKINS",
  shopTracks: "SOUNDTRACKS",
  shopBack: "VOLVER",
  shopOpen: "TIENDA",
  stBought: "COMPRADO",
  stEquipped: "EQUIPADO",
  stEquip: "EQUIPAR",
  stBuy: "COMPRAR",
  stFree: "GRATIS",
  stLocked: "BLOQUEADO",
  stInsufficient: "SALDO INSUFICIENTE",
  // nombres de items (skins + soundtracks) por datos
  skinDefault: "CROMO CLASICO",
  skinCyan: "AZUL ELÉCTRICO",
  skinMagenta: "MAGENTA HEAT",
  skinGold: "ORO BUSTER",
  skinViolet: "VIOLETA NOVA",
  skinAqua: "AQUA GRID",
  abMoney: "MONEDAS X2",
  abShield: "INVENCIBLE",
  abLife: "VIDA EXTRA",
  trackBase: "NEON BASE",
  track01: "NIGHT DRIVE",
  track02: "MIDNIGHT CRUISE",
  track03: "OUTRUN CHASE",
  track04: "SUNSET DREAM",
  track05: "TURBO BOOST",
};
